name: CI-CD
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Install dependencies
        run: |
          npm install
      - name: build
        run: |
          CI='' npm run build
          npm test ./App.test.js
     
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}     
          
      - name: Build and push Docker images
      # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./
          file: ./Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/react:latest
          image: 'sabean365/react:latest'
          registry: docker.io
         
